version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_produtos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controle_produtos
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
